version: "5"
services:
  django:
    build:
      context: .
      dockerfile: ./docker_env/django/Dockerfile
    container_name: django
    working_dir: /backend
    ports:
      - "8000:8000"
    expose:
      - "8000"
    command: daphne -b 0.0.0.0 -p 8000 --proxy-headers application.asgi:application
    restart: always
    volumes:
      - ./backend:/backend
      - ./docker_env/django/logs:/var/log